# Generated by Django 3.2.6 on 2021-08-22 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscribe_is_active',
            field=models.BooleanField(default=False, verbose_name='Подписка активна'),
        ),
    ]
